### PR TITLE
Add Catppuccin Mocha to the available UI themes

### PR DESCRIPTION
**Pull request by TheBearodactyl**
just as the title suggests, I added catppuccin mocha to the available UI themes

### CODE REVIEW

**Comment by qimiko** [comment]
:o 
just wondering, what was your reference for the theme? not too sure about the contrast between the button text and background color

**Comment by TheBearodactyl** [comment]
> :o just wondering, what was your reference for the theme? not too sure about the contrast between the button text and background color

I used the official cattpuccin palette :D
https://github.com/catppuccin/palette

**Comment by pauliesnug** [comment]
> :o just wondering, what was your reference for the theme? not too sure about the contrast between the button text and background color

i think the colors themselves are up to catppuccin spec, but the combination/applied elements might not be? i do agree the contrast is probably too little...

**Pull request closed without merging**
