### PR TITLE
Add vibration permission

### PR DESCRIPTION
**Pull request by undefined06855**
I've seen people in the past want this so might as well do it but this needs to be added in the manifest for it to work

### CODE REVIEW

**Comment by undefined06855** [comment]
also this is untested so i hope it works

**Comment by TheSillyDoggo** [comment]
geometry plug for android ❤️

**Comment by undefined06855** [comment]
will test now

**Comment by undefined06855** [comment]
ok so i havent been testing but eventually i might so idk well ill close it for now but eventually might reopen

**Pull request closed without merging**
